config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/apple.rb
class Apple < ActiveRecord::Base
  belongs_to :mother
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/husband.rb
class Husband < ActiveRecord::Base
  belongs_to :wife
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :student
  belongs_to :teacher
end

app/models/mother.rb
class Mother < ActiveRecord::Base
  has_many :sons
end

app/models/son.rb
class Son < ActiveRecord::Base
  belongs_to :mother
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :lessons
  has_many :teachers, :through => :lessons
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :lessons
  has_many :students, :through => :lessons
end

app/models/wife.rb
class Wife < ActiveRecord::Base
  has_one :husband
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :get_by_id, :only => [:show, :destroy, :edit, :update]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create

    Book.create params[:book]
    redirect_to books_path
  end

  def edit
  end

  def update
    #@book.title = params[:title]
    #@book.author = params[:author]
    #@book.save

    puts "== params: "
    puts params.inspect

    @book.update params[:book]

    redirect_to books_path
  end

  def show
  end


  def destroy
    @book.delete
    redirect_to books_path
  end

  private
  def get_by_id
    @book = Book.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  标题:  <%= f.text_field :title %><br/>
  作者:  <%= f.text_field :author %><br/>
  <%= f.submit %>

<% end %>

app/views/books/edit.html.erb
<h3> 编辑Book页</h3>

<%= render :partial => 'form' %>

<!--
<form action='/books/<%= @book.id %>' method=POST>
  <input type='hidden' name='_method'  value='PUT'/>

  标题:  <input type='text' name='title' value='<%= @book.title %>'/> <br/>
  作者: <input type='text' name='author' value='<%= @book.author %>' /> <br/>

  <input type='submit' />
</form>
-->

app/views/books/index.html.erb
<h3>Book 列表页</h3>

<table>
  <tr>
    <td>标题</td>
    <td>作者</td>
    <td>操作</td>
  <tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book %></td>
      <td><%= book.author %></td>
      <td>
        <%= link_to "编辑", edit_book_path(:id => book.id) %>
        <%= link_to "删除", book, :method => :delete  %>
      </td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to "新建" , new_book_path %>

<img src='<%= asset_path 'linux.jpg' %>' />

app/views/books/new.html.erb
<h3> 新建Book页</h3>

<%= render :partial => 'form' %>

<!--
<form action='/books' method=POST>

  标题:  <input type='text' name='title'/> <br/>
  作者: <input type='text' name='author'/> <br/>

  <input type='submit' />
</form>
-->

app/views/books/show.html.erb
<h3>详情页</h3>

title: <%= @book.title %><br/>
author: <%= @book.author %><br/>

<%= link_to '列表页', books_path %>

app/views/layouts/a.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>我是布局A</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>学习Rails的布局</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/b.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>我是布局B</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div>
</div>
</body>
</html>